export { default as About } from './About/About';
export { default as Footer } from './Footer/Footer';
export { default as Header } from './Header/Header';
export { default as AquaticAbout } from './AquaticAbout/AquaticAbout';
export { default as AquaticHeader } from './AquaticHeader/AquaticHeader';
export { default as AquaticTeam } from './AquaticTeam/AquaticTeam';
export { default as AquaticTestimonial } from './AquaticTestimonial/AquaticTestimonial';
export { default as AquaticWork } from './AquaticWork/AquaticWork';
export { default as TechAbout } from './TechAbout/TechAbout';
export { default as TechHeader } from './TechHeader/TechHeader';
export { default as TechTestimonial } from './TechTestimonial/TechTestimonial';
export { default as MeetTheCeo } from './MeetTheCeo/MeetTheCeo';
export { default as SolarHeader } from './SolarHeader/SolarHeader';
export { default as SolarAbout } from './SolarAbout/SolarAbout';
export { default as SolarProjects } from './SolarProjects/SolarProjects';
export { default as SolarTestimonial } from './SolarTestimonial/SolarTestimonial';
export { default as ConstructionAbout } from './ConstructionAbout/ConstructionAbout'
export { default as ConstructionHeader } from './ConstructionHeader/ConstructionHeader'
export { default as ConstructionProjects } from './ConstructionProjects/ConstructionProjects'
export { default as ConstructionTestimonials } from './ConstructionTestimonials/ConstructionTestimonials'
export { default as OurTeam } from './OurTeam/OurTeam';
